# Base URL used when generating links to your pages
# Set to the URL for your site
baseurl = "https://ouspg.github.io/ShakingUpTech/"
defaultContentLanguage = "fi"
theme = 'terminal'
paginate = 5

# Basic metadata configuration for your blog.
title = "Shaking up Tech 13.10.2022"
author = "OUSPG"
languageCode = "fi-FI"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
  themeColor = "orange"

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
  favicon = "images/favicon.png"
  centerTheme = true 

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.

[params.logo]
      logoHomeLink = "/ShakingUpTech"

[languages]
  [languages.fi]
    languageName = "Suomi"
    title = "Shaking Up Tech 13.10.2022"
    subtitle = "Kryptoteemainen työpaja"
    owner = ""
    keywords = ""
    copyright = "Oulu University Secure Programming Group"
    menuMore = "Näytä enemmän"
    readMore = "Lue lisää"
    readOtherPosts = "Lue muut artikkelit"
    newerPosts = "Uudemmat artikkelit"
    olderPosts = "Vanhemmat artikkelit"
    missingContentMessage = "Sivusto ei löytynyt..."
    missingBackButtonLabel = "Palaa etusivulle"

    [languages.fi.params.logo]
      logoText = "Shaking up Tech"
      logoHomeLink = "/ShakingUpTech"

    [languages.fi.menu]
      [[languages.fi.menu.main]]
        Weight = 1
        identifier = "harjoitus1"
        name = "Täydellinen salausmenetelmä?"
        url = "/harjoitus1"
      [[languages.fi.menu.main]]
        Weight = 2
        identifier = "harjoitus2"
        name = "Moderni salaus"
        url = "/harjoitus2"
      [[languages.fi.menu.main]]
        Weight = 3
        identifier = "ascii"
        name = "ASCII Taulukko"
        url = "/ascii"
      [[languages.fi.menu.main]]
        Weight = 4
        identifier = "CyberChef"
        name = "CyberChef"
        url = "https://gchq.github.io/CyberChef/"
        pre = "_blank"
