# Base URL used when generating links to your pages
# Set to the URL for your site
baseurl = "/"
defaultContentLanguage = "fi"

# The name of this wonderful theme ;-).
theme = 'terminal'
paginate = 5

# Basic metadata configuration for your blog.
title = "Shaking Up Tech 13.10.2022"
author = "OUSPG"
#  copyright = "Copyright © 2020, Jane Doe."
languageCode = "fi-FI"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
  themeColor = "orange"

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
  favicon = "images/favicon.png"
  centerTheme = true 

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.

[languages]
  [languages.fi]
    languageName = "Suomi"
    title = "Shaking Up Tech 13.10.2022"
    subtitle = "A simple, retro theme for Hugo"
    owner = ""
    keywords = ""
    copyright = "Oulu University Secure Programming Group"
    menuMore = "Näytä enemmän"
    readMore = "Lue lisää"
    readOtherPosts = "Read other posts"
    newerPosts = "Uudemman artikkelit"
    olderPosts = "Vanhemmat artikkelit"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.fi.params.logo]
      logoText = "Shaking Up Tech"
      logoHomeLink = "/"

    [languages.fi.menu]
      [[languages.fi.menu.main]]
        identifier = "ascii"
        name = "ASCII taulukko"
        url = "/ascii"
